Feat/udp add udp protocol
recursion-b/Online_Chat_Messenger pull request #12
Opened 2023-09-30 12:07 UTC by harutas

### 実装内容
- UDPのプロトコル作成
- TCP切断後に自動でUDPでサーバへメッセージを送り、サーバーにUDPのアドレスを登録させる。

**UDPプロトコル**
ヘッダー(2byte)：RoomNameSize（1）| TokenSize（1バイト）
ボディ(max 4094)：最初のRoomNameSizeバイトはルーム名、次のTokenSizeバイトはトークン文字列、その残りが実際のメッセージ

2023-09-30 12:10 UTC, harutas commented on stage2/server.py
> +                    tcp_addr=addr, access_token=token, username=user_name
TCP接続時にuser_nameを送信してるので、初期化時にuser_name追加してます。

2023-09-30 16:23 UTC, Hayato-Kossy commented on stage2/server.py
> +                    tcp_addr=addr, access_token=token, username=user_name
最新のdevelopに合わせた修正ってやってもらえますかね

UDPのreceive_messageとかそこらへんが修正必要な感じでした

JSONとかは自由にしてもらって構いません

2023-09-30 16:24 UTC, Hayato-Kossy requested changes
最新のdevに合わせた修正をお願いしたい

2023-10-01 02:18 UTC, harutas commented
developに合わせて修正しました。
room_nameとかtokenをJSONで送るようにすると、UDPのヘッダーとかいらない気がしてきました。
一応、ヘッダーは残して、JSONの長さだけ確認できるようにしてますが、使うところないです。

**動作確認**
![image](https://github.com/recursion-b/Online_Chat_Messenger/assets/96802323/6712c3a5-8d2c-442c-942e-dbfa74f5b73b)

2023-10-01 04:14 UTC, Hayato-Kossy commented
> developに合わせて修正しました。 一応、ヘッダーはJSONの長さを取得できるようにしてるので、後ほどメッセージサイズのバリデーションを付けます。
> 
> **動作確認** ![image](https://user-images.githubusercontent.com/96802323/271804517-6712c3a5-8d2c-442c-942e-dbfa74f5b73b.png)

スクショ貼るのとかめっちゃいいっすね！ありがたいっす！

2023-10-01 04:16 UTC, Hayato-Kossy approved these changes
完璧っす

2023-10-01 04:16 UTC, merged