ChatRoomクラスの作成、それに伴うリファクタリング
recursion-b/Online_Chat_Messenger pull request #20
Opened 2023-10-02 02:35 UTC by AkinoJoey

チャットルームクラス作成して、それに伴ってリファクタリングしました！

2023-10-02 11:45 UTC, harutas requested changes
実装ありがとうございます！
1点確認お願いします！

2023-10-02 11:45 UTC, harutas commented on stage2/server.py
> +        return clients_to_remove
inactivity_thresholdを引数で渡すのではなく、
ChatRoomのクラス変数に持たせるのがいいと思いました。
```
Class ChatRoom:
    inactivity_threshold = 30
    def __init__(self, room_name):
        self.room_name = room_name
        self.client_infos = []
```

2023-10-02 12:09 UTC, harutas commented on stage2/server.py
> +
チャットルームの情報が分かるように、__repr__を定義してもいいかもしれないですね。
```suggestion
    def __repr__(self):
        repr_string = ""
        for client_info in self.client_infos:
            repr_string += f"<ClientInfo(udp_addr={client_info.udp_addr}, tcp_addr={client_info.tcp_addr}, access_token={client_info.access_token}, username={client_info.username}, is_host={client_info.is_host})>"

        return repr_string
```

2023-10-03 01:08 UTC, AkinoJoey commented on stage2/server.py
> +        return clients_to_remove
それか、 inactivity_thresholdは他で使う予定はないですし、変数宣言はなるべく使用される直前が良いと思いますので、ローカル変数として持たせるのはどうでしょうか？？
```
def find_inactive_clients(self) -> list:
        clients_to_remove = []

        for client_info in self.client_infos:
            inactivity_threshold = 30
            if (
                time.time() - client_info.last_message_time > inactivity_threshold
            ):  
```

2023-10-03 03:03 UTC, harutas commented on stage2/server.py
> +        return clients_to_remove
確かにどこからでもアクセスできたら困りますね
それでお願いします🙏

2023-10-03 03:11 UTC, AkinoJoey commented on stage2/server.py
> +
実装しました！ClientInfoクラスで__repr__が定義されているので、以下で動きました！
```
def __repr__(self):
        return (
            f"<ChatRoom(room_name={self.room_name}, client_infos={self.client_infos})>"
        )
```

2023-10-03 03:54 UTC, harutas approved these changes
ありがとうございます！

2023-10-03 07:18 UTC, Hayato-Kossy approved these changes
コメントアウトでコンフリクトしていましたがまあいいでしょと思ってこちらで解決しました

2023-10-03 07:18 UTC, merged